---
- name: Checking out Variable Arrays
  hosts: all
  vars:
    group1:
      amigo:
        name: user1
        groups: wheel
    group2:
      notamigo:
        name: user2
        groups: wheel
  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
      loop:
        - "{{ group1.amigo }}"
        - "{{ group2.notamigo }}"
