---
- name: Setting a user hashed password
  hosts: all
  tasks:
  - name: Creating the hashed password
    debug:
      msg: "{{ 'love' | password_hash('sha512','testing') }}"
    register: debugpassword
 
  - name: debug the debug
    debug:
      var: debugpassword.msg

  - name: Create user with hashed password
    user:
      name: maria
      group: wheel
      password: "{{ debugpassword.msg }}"
