---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Change user password
      user:
        name: nameofuser
        update_password: always
        password: "{{ 'Th1Sisv3ry@wes0m3r1GHT'|password_hash('sha512') }}"



### yum install python3-pip -y ---> Install pip
### pip install passlib  ---> Password Hashing Library in Python

