---
- name: Working with pre-tasks and post-tasks
  hosts: all
  post_tasks:
  - name: post-tasks
    debug:
      msg: This is {{ ansible_distribution }}
  - name: debug using var
    debug:
      var: ansible_os_family

  pre_tasks:
  - name: pre-tasks
    user:
      name: maria
