### Template is useful if you want to copy configuration files that contain dynamic information. Create file on Control Node using variables. Change the values of the variables within the playbook to update the file on different servers###

---
- name: Working with jinja2 templates
  hosts: servername
  tasks:
  - name: Copy template file from control node to mananged node
    template:
      src: /root/fileoncontrolnode
      dest: /tmp/fileonremoteserver
  vars:
    name1: Kelly
    name2: Michelle
    name3: Sonia
    car1: Honda
    car2: Toyota
    car3: Lexus


- name: Working with jinja2 templates
  hosts: all
  tasks:
  - name: Copy template file from control node to mananged node
    template:
      src: hosts.j2
      dest: /tmp/hostsfile

### Create directory called templates and store the jinja2 files under it ###
