---
- hosts: all
  gather_facts: no
  tasks:
  - systemd:
      name: "{{name}}"
      state: "{{status}}"
    register: service_output
  - debug:
      msg:
      - "Name of Service: {{service_output.name}}"
      - "State of Service: {{service_output.state}}"
